const mock=[
  {speaker:"Homer Simpson",quote:"Ao álcool... A causa e solução de todos os problemas."},
  {speaker:"Homer Simpson",quote:"Se alguma coisa está difícil de ser feita, é porque não é para ser feita!."},
  {speaker:"Homer Simpson",quote:"Crianças, vocês tentaram e falharam miseravelmente. A lição é: nunca tente."},
  {speaker:"Homer Simpson",quote:"Oh não, alienígenas espaciais! Por favor, não me comam! Eu tenho mulher e filhos. Comam eles!"},
  {speaker:"Homer Simpson",quote:"Eu tenho três filhos e nenhum dinheiro. Por que eu não posso ter nenhum filho e três dinheiros?"},
  {speaker:"Homer Simpson",quote:"Pessoas inventam estatísticas para provar qualquer coisa. 14% das pessoas sabem disso"},
  {speaker:"Homer Simpson",quote:"Bart, diferente do amor, o respeito não pode ser comprado"},
  {speaker:"Homer Simpson",quote:"Não importa o quão bom você é em alguma coisa. Existem mais ou menos 1 milhão de pessoas melhores do que você fazendo a mesma coisa"},
  {speaker:"Homer Simpson",quote:"Nunca diga qualquer coisa a não ser que tenha certeza de que todo mundo pensa o mesmo"},
  {speaker:"Homer Simpson",quote:"Chorar não vai trazer de volta seu cão, a não ser que suas lágrimas tenham cheiro de ração"},
  {speaker:"Homer Simpson",quote:"As respostas para todos os problemas da vida não estão no fundo de uma garrafa. Estão na TV!"},
  {speaker:"Homer Simpson",quote:"Só porque eu não me importo não significa que eu não entenda"},
  {speaker:"Homer Simpson",quote:"Lisa, se você não gosta do seu emprego, você não faz uma greve! Você vai lá todo dia e faz seu trabalho malfeito! Esse é o ‘Jeito Americano’!"},
  {speaker:"Homer Simpson",quote:"Filho, se você realmente quer algo nesta vida, você tem que trabalhar para isso. Agora, quieto! Eles vão anunciar os números da loteria"},
  {speaker:"Homer Simpson",quote:"E olha que eu não sou uma pessoa que se impressiona facilmente... Hey, olhe, um carro azul!"},
  {speaker:"Homer Simpson",quote:"Filho, essas são as 3 frases que o farão passar pela vida: - Pega isso aí­ pra mim. - Boa idéia, patrão! - Já estava assim quando eu cheguei."},
  {speaker:"Homer Simpson",quote:"Você pode ter todo o dinheiro do mundo, mas há algo que jamais poderá comprar: um dinossauro!"},
  {speaker:"Homer Simpson",quote:"Ora, Marge, se Deus não quisesse que a gente comesse na igreja, não teria colocado a gula como pecado?"},
  {speaker:"Homer Simpson",quote:"A culpa é minha, eu coloco ela em quem eu quiser."},
  {speaker:"Homer Simpson",quote:"Deus é o personagem de ficção que eu mais gosto!"},
  {speaker:"Homer Simpson",quote:"Meu segundo nome é Paciência, e o primeiro é Sem."},
  {speaker:"Homer Simpson",quote:"Eu não sou um cara mal, eu trabalho duro e amo meus filhos. Então por que eu deveria perder metade do meu domingo ouvindo como eu vou pro inferno?!"},
  {speaker:"Homer Simpson",quote:"Gostaria que Deus estivesse vivo para ver isto!"},
  {speaker:"Homer Simpson",quote:"Não costumo ser um homem religioso, mas se tu estás lá em cima, me salva, SUPER-HOMEM!"},
  {speaker:"Homer Simpson",quote:"Eu não estava mentindo! Estava escrevendo ficção com a boca."},
  {speaker:"Homer Simpson",quote:"Preguiça é o ato de descansar, antes de estar cansado!"},
  {speaker:"Homer Simpson",quote:"A TV me respeita. Ela ri comigo e não de mim."},
  {speaker:"Homer Simpson",quote:"Existem três jeitos de fazer as coisas: o jeito certo, o jeito errado, e o meu jeito, que é igual ao jeito errado, só que mais rápido."},
  {speaker:"Homer Simpson",quote:"Eu não bebo água… os peixes transam nela."},
  {speaker:"Homer Simpson",quote:"Se um dia você perder o controle, levante-se e troque o canal manualmente."},
  {speaker:"Homer Simpson",quote:"Tentar é o primeiro passo rumo ao fracasso."},
  {speaker:"Homer Simpson",quote:"O casamento é o caixão, os filhos são os pregos."},
  {speaker:"Homer Simpson",quote:"Sair de casa pra que? De qualquer jeito vou acabar voltando pra cá!"},
  {speaker:"Homer Simpson",quote:"Bart, com US$ 10.000 vamos ficar milionários. Poderemos comprar todo tipo de coisas úteis como… Amor."},
  {speaker:"Homer Simpson",quote:"Não se pode culpar constantemente. Culpe-se só uma vez e vá em frente."},
  {speaker:"Homer Simpson",quote:"Quando vejo crianças a sorrir, já sei que estão aprontando alguma coisa."},
  {speaker:"Homer Simpson",quote:"Passei a detestar minha propria criaçao, agora sei como Deus se sente."},
  {speaker:"Homer Simpson",quote:"A vingança é um prato que se come três vezes ao dia."},
  {speaker:"Homer Simpson",quote:"Se você não faz parte da solução, faz parte do problema!!!"},
  {speaker:"Homer Simpson",quote:"Se não pode ajudar, atrapalhe, o importante é participar!"},
  {speaker:"Homer Simpson",quote:"Por que as coisas que acontecem com gente burra ficam acontecendo comigo?"},
  {speaker:"Homer Simpson",quote:"Deus, se quiseres que eu coma as oferendas não se manifeste de nenhuma maneira... ... Tua vontade será feita..."}
];

export default mock;